name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  quality:
    name: Quality Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9.13.2

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm build --noEmit

      - name: Lint
        run: pnpm eslint . --ext .ts,.tsx

      - name: Format check
        run: pnpm prettier --check "src/**/*.{ts,tsx,json,md}"

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   needs: quality

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: 8

  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'
  #         cache: 'pnpm'

  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile

  #     - name: Run tests
  #       run: pnpm test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [quality]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9.13.2

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      # Optional: Add build artifact upload
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/
          retention-days: 7
